stages:
  data_ingestion:
    cmd: python src/data_preprocess/data_ingestion.py
    deps:
      - src/data_preprocess/data_ingestion.py
      - src/connections/s3_connections.py 
    outs:
      - data/ingested/data.xlsx

  data_preprocessing:
    cmd: python src/data_preprocess/data_preprocessing.py
    deps:
      - src/data_preprocess/data_preprocessing.py
      - data/ingested/data.xlsx
    outs:
      - data/processed/data.csv

  feature_engineering:
    cmd: python src/feature_engineering/feature_engineering.py
    deps:
      - src/feature_engineering/feature_engineering.py
      - src/connections/s3_connections.py 
      - data/processed/data.csv  

    outs:
      - data/interim/X_train.csv
      - data/interim/X_test.csv
      - data/interim/y_train.csv
      - data/interim/y_test.csv
      - data/visualization_data/data.csv

  data_transformation:
    cmd: python src/data_transformation/data_transformation.py
    deps:
      - src/data_transformation/data_transformation.py
      - data/processed/data.csv
    outs:
      - data/transformed/X_train.csv
      - data/transformed/X_test.csv
      - data/transformed/y_train.csv
      - data/transformed/y_test.csv
      - models/transformer.pkl

  model_training:
    cmd: python src/model/model_trainer.py
    deps:
      - src/model/model_trainer.py
      - data/transformed/X_train.csv
      - data/transformed/y_train.csv
    outs:
      - models/model.pkl
 

  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
      - src/model/model_evaluation.py
      - models/model.pkl
      - data/transformed/X_test.csv
      - data/transformed/y_test.csv



  register_model:
    cmd: python src/model/register_model.py
    deps:
      - src/model/register_model.py

